# 应用服务 WEB 访问端口
server:
  port: 8081
  servlet:
    #访问路径
    context-path: /lsp

# 应用名称
spring:
  application:
    name: lsp-pan
  mvc:
    pathmatch:
      # 配置文档策略
      matching-strategy: ant-path-matcher
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/lsp_pan?characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    # 上传文件配置
    multipart:
      enabled: true
      max-file-size: 3MB        #最大文件限制
      max-request-size: 3MB     #最大请求限制
      file-size-threshold: 5MB  #文件超出此大小写入磁盘缓存
      location: /               #磁盘缓存路径
  # redis 配置
  redis:
    host: 127.0.0.1
    password: '123456'

# jwt token
jwt:
  secret: i'm a lsp

#  #spring security配置
#  security:
#    user:
#      name: admin
#      password: admin
#      roles: admin

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis-plus:
  mapper-locations: classpath*:com/booker/lsp/mapper/**/*.xml
  #指定Mybatis的实体目录
  type-aliases-package: com.booker.lsp.entity
  #日志显示sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#文件根目录
fileUpConfig:
  rootDir: D:\rootDir
  tempDir: D:\rootDir\temp


